#!/bin/bash

##############################################

#Script Name: Touch Assignment

#Purpose: Create 1 or more files for holberton assignments based off of blank templates

#Arguments: None, but user is prompted for template and file name

#Author: Brett Davis

#Version: 0.2

##############################################


#Initialize template filepaths
base=0
bash=~/scripts/templates/bash.template
empty=~/scripts/templates/empty.template
html=~/scripts/templates/html.template
cTemp=~/scripts/templates/c.template
cPlusplus=~/scripts/templates/cplusplus.template
java=~/scripts/templates/java.template


#Prompt user for template to use
function select_template () {
echo "Enter the desired template for all files created.
OPTIONS MENU
c - c++ - java
html - bash - empty
executable"
read templateStr
case $templateStr in
    c | C)
	template=$cTemp
	;;
    html | HTML | Html)
	template=$html
	;;
    bash | Bash | BASH)
	template=$bash
	perms="executable"
	;;
    empty | EMPTY | "")
	template=$empty
	;;
    executable | x | EXECUTABLE)
	template=$empty
	perms="executable"
	;;
    java | JAVA | Java)
	template=$java
	;;
    c++ | C++ | cplusplus | Cplusplus | CPlusPlus)
	template=$cPlusplus
	;;
    *)
	template=$empty
esac
}
function fileName () {
#Infinite while loop
while [ true ]
do
    echo Enter the desired filename or press q to quit. You may also press t to change template.
    read fName


#Break the loop if user enter q
    if [ "$fName" == "q" ];
	then break;
    fi

#Calls select_template if user presses t
    if [ "$fName" == "t" ]
	then 
	select_template
	fileName
	break
    fi

#Create the file and initialize it with the chosen template
    touch "$fName"
    cat $template > ./$fName


#Adds potential for variable perms based on template later
    case $perms in
	executable)
	    chmod u+x ./$fName
	    ;;
	*)
    esac
done
}
select_template
fileName
exit
