#!/bin/bash

##############################################

#Script Name: Touch Assignment

#Purpose: Create 1 or more files for holberton assignments based off of blank templates

#Arguments: None, but user is prompted for template and file name

#Author: Brett Davis

#Version: 0.1

##############################################


#Initialize template filepaths
base=0
bash=~/scripts/templates/bash.template
empty=~/scripts/templates/empty.template
html=~/scripts/templates/html.template
cTemp=~/scripts/templates/c.template


#Prompt user for template to use
echo Enter the desired template for all files created. Templates include 'c', 'html', 'bash', and 'empty'. If no template is selected, default to empty.
read templateStr
case $templateStr in
    c | C)
	template=$cTemp
	;;
    html | HTML)
	template=$html
	;;
    bash)
	template=$bash
	perms="executable"
	;;
    empty | EMPTY | "")
	template=$empty
	;;
    *)
esac

#Infinite while loop
while [ true ]
do
    echo Enter the desired filename or press q to quit
    read fName


#Break the loop if user enter q
    if [ "$fName" == "q" ];
	then break;
    fi

#Create the file and initialize it with the chosen template
    touch "$fName"
    cat $template > ./$fName


#Adds potential for variable perms based on template later
    case $perms in
	executable)
	    chmod u+x ./$fName
	    ;;
	*)
    esac
done
